name = "docbuild"
reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"

[[require]]
name = "formal_conjectures"
path = "../"

[[require]]
name = "verso"
git = "https://github.com/mo271/verso.git"
rev = "5ce19c4a239e2d0ed4153399bd17957cffff0535"
