/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil

/-!
# Erdős Problem 433

*References:*
- [Erdős Problem 433](https://www.erdosproblems.com/433)
- P. Erdős and R. L. Graham, *On a linear Diophantine problem of Frobenius*,
  Acta Arithmetica 21 (1972), 399–408.
- J. Dixmier, *Proof of a conjecture by Erdős and Graham on Frobenius' coin problem*,
  Proceedings of the AMS 109 (1990), 567–577.
-/

namespace Erdos433

open Filter
open scoped Topology

/-- The Frobenius number of a finite set $A$: the greatest natural number outside the
additive submonoid generated by $A$. -/
noncomputable def frobeniusNumber (A : Finset ℕ) : ℕ :=
  sSup {m | m ∉ AddSubmonoid.closure (A : Set ℕ)}

/-- The largest Frobenius number of a $k$-element subset of $\{1,\ldots,n\}$ whose
elements have greatest common divisor one. -/
noncomputable def g (k n : ℕ) : ℕ :=
  sSup {m | ∃ A : Finset ℕ, A ⊆ Finset.Icc 1 n ∧ A.card = k ∧ A.gcd id = 1 ∧
    m = frobeniusNumber A}

/-- For every fixed $k \geq 2$, Erdős and Graham conjectured that
$$g(k,n) \sim \frac{n^2}{k-1}.$$
The conjecture was proved by Dixmier [Di90]. -/
@[category research solved, AMS 11]
theorem erdos_433 : answer(True) ↔ ∀ k, 2 ≤ k →
    Tendsto (fun n : ℕ => (g k n : ℝ) / ((n : ℝ) ^ 2 / ((k : ℝ) - 1))) atTop (𝓝 1) := by
  sorry

end Erdos433
