/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil
import FormalConjectures.Wikipedia.Hadamard

/-!
# The circulant Hadamard conjecture

A circulant matrix is generated by cyclically shifting one row. The circulant Hadamard conjecture,
also attributed to Ryser, says that no circulant Hadamard matrix has order greater than $4$.

*Reference:*
* S. Steinerberger,
  [A note on approximate Hadamard matrices](https://arxiv.org/abs/2402.13202)
-/

namespace CirculantHadamard

/-- A generator for a circulant Hadamard matrix of order four. -/
def orderFourGenerator : Fin 4 → ℝ :=
  ![1, 1, 1, -1]

/-- The order-four generator gives a circulant Hadamard matrix. -/
@[category test, AMS 15]
theorem orderFourGenerator_isHadamard :
    Hadamard.IsHadamard' (Matrix.circulant orderFourGenerator) := by
  constructor
  · intro i j
    fin_cases i <;> fin_cases j <;>
      norm_num [Matrix.circulant, orderFourGenerator, Fin.sub_def, Fin.neg_def]
  · ext i j
    fin_cases i <;> fin_cases j <;>
      norm_num [Matrix.mul_apply, Matrix.circulant, orderFourGenerator, Fin.sum_univ_succ,
        Fin.sub_def, Fin.neg_def, Matrix.ofNat_apply]

/-- Every circulant Hadamard matrix has order at most four. -/
@[category research open, AMS 15]
theorem circulant_hadamard_conjecture {n : ℕ} (v : Fin n → ℝ)
    (hv : Hadamard.IsHadamard' (Matrix.circulant v)) : n ≤ 4 := by
  sorry

end CirculantHadamard
